import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, EmptyState, LoadingScreen, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { customerHasOverdueCredit, formatKes, getCreditBalance } from "@/lib/stockbook/calculations";
import { useStockbook } from "@/lib/stockbook/store";
import { useColors } from "@/hooks/use-colors";

export default function CreditScreen() {
  const { state, ready } = useStockbook(); const colors = useColors();
  const customers = useMemo(() => state.customers.map((customer) => ({ customer, balance: getCreditBalance(state, customer.id), overdue: customerHasOverdueCredit(state, customer) })).filter((item) => item.balance > 0).sort((a, b) => b.balance - a.balance), [state]);
  const outstanding = customers.reduce((sum, item) => sum + item.balance, 0); const overdue = customers.filter((item) => item.overdue).reduce((sum, item) => sum + item.balance, 0);
  if (!ready) return <LoadingScreen />;
  return <Screen><TopBar title="Credit Book" subtitle="Track what customers owe" onBack={() => router.back()} action={<Pressable accessibilityRole="button" accessibilityLabel="Add customer" onPress={() => router.push({ pathname: "/customer" as any, params: { mode: "new" } })} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="person-add" size={20} color="#FFFFFF" /></Pressable>} /><View style={styles.metrics}><Metric label="Outstanding" value={formatKes(outstanding)} /><Metric label="Customers" value={String(customers.length)} /><Metric label="Overdue" value={formatKes(overdue)} danger={overdue > 0} /></View>{customers.length ? <Card style={styles.list}>{customers.map((item, index) => <Pressable key={item.customer.id} accessibilityRole="button" onPress={() => router.push({ pathname: "/customer" as any, params: { customerId: item.customer.id } })} style={({ pressed }) => [styles.row, index !== customers.length - 1 && { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, { opacity: pressed ? 0.68 : 1 }]}><View style={[styles.avatar, { backgroundColor: `${colors.primary}16` }]}><Text style={{ color: colors.primary, fontWeight: "800" }}>{item.customer.name.slice(0, 1).toUpperCase()}</Text></View><View style={{ flex: 1 }}><View style={styles.nameRow}><Text style={[styles.name, { color: colors.text }]}>{item.customer.name}</Text>{item.overdue ? <Text style={{ color: colors.error, fontSize: 10, fontWeight: "800" }}>OVERDUE</Text> : null}</View><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>{item.customer.phoneNumber || "No phone saved"}</Text></View><View style={{ alignItems: "flex-end" }}><Text style={{ color: item.overdue ? colors.error : colors.text, fontWeight: "800" }}>{formatKes(item.balance)}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 3 }}>owed</Text></View></Pressable>)}</Card> : <EmptyState icon="group" title="No outstanding credit" detail="Credit sales will appear here. You can also add a customer before recording a credit sale." action={<PrimaryButton label="Add customer" icon="person-add" onPress={() => router.push({ pathname: "/customer" as any, params: { mode: "new" } })} full={false} />} />}</Screen>;
}
function Metric({ label, value, danger }: { label: string; value: string; danger?: boolean }) { const colors = useColors(); return <Card style={styles.metric}><Text style={{ color: colors.muted, fontSize: 11, fontWeight: "700" }}>{label}</Text><Text style={{ color: danger ? colors.error : colors.text, fontSize: 16, fontWeight: "800", marginTop: 7 }} numberOfLines={1}>{value}</Text></Card>; }
const styles = StyleSheet.create({ add: { width: 44, height: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, metrics: { flexDirection: "row", gap: 8, marginBottom: 15 }, metric: { flex: 1, padding: 11, minHeight: 82 }, list: { paddingVertical: 1 }, row: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10 }, avatar: { width: 39, height: 39, borderRadius: 13, alignItems: "center", justifyContent: "center" }, nameRow: { flexDirection: "row", alignItems: "center", gap: 6 }, name: { fontSize: 14, fontWeight: "800" } });
