import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Chip, Field, KeyValue, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { formatKes, getCreditBalance } from "@/lib/stockbook/calculations";
import { useStockbook } from "@/lib/stockbook/store";
import { useColors } from "@/hooks/use-colors";
import type { PaymentMethod } from "@/lib/stockbook/types";

export default function CustomerScreen() {
  const { customerId, mode } = useLocalSearchParams<{ customerId?: string; mode?: string }>(); const { state, addCustomer, addCreditPayment } = useStockbook(); const colors = useColors(); const customer = state.customers.find((entry) => entry.id === customerId);
  const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [note, setNote] = useState(""); const [amount, setAmount] = useState(""); const [method, setMethod] = useState<PaymentMethod>("cash"); const [paymentNote, setPaymentNote] = useState("");
  const add = () => { try { addCustomer({ name, phoneNumber: phone.trim() || undefined, notes: note.trim() || undefined }); router.back(); } catch (error) { Alert.alert("Could not add customer", error instanceof Error ? error.message : "Check the details."); } };
  if (mode === "new" || !customer) return <Screen><TopBar title="Add customer" onBack={() => router.back()} /><Field label="Customer name" value={name} onChangeText={setName} placeholder="Full name" /><Field label="Phone number (optional)" value={phone} onChangeText={setPhone} placeholder="07…" keyboardType="phone-pad" /><Field label="Note (optional)" value={note} onChangeText={setNote} placeholder="Helpful details" multiline /><PrimaryButton label="Add customer" icon="person-add" onPress={add} /></Screen>;
  const balance = getCreditBalance(state, customer.id); const sales = state.sales.filter((sale) => sale.customerId === customer.id && sale.paymentMethod === "credit"); const payments = state.creditPayments.filter((payment) => payment.customerId === customer.id);
  const record = () => { try { addCreditPayment({ customerId: customer.id, amount: Number(amount), paymentMethod: method, note: paymentNote.trim() || undefined, paymentDate: new Date().toISOString() }); setAmount(""); setPaymentNote(""); Alert.alert("Payment recorded", "The outstanding balance has been updated."); } catch (error) { Alert.alert("Could not record payment", error instanceof Error ? error.message : "Check the payment details."); } };
  const contact = (kind: "tel" | "sms") => { if (!customer.phoneNumber) { Alert.alert("No phone number", "Add a number to call or message this customer."); return; } void Linking.openURL(`${kind}:${customer.phoneNumber}`); };
  return <Screen><TopBar title={customer.name} subtitle={customer.phoneNumber || "No phone number"} onBack={() => router.back()} /><Card style={[styles.balanceCard, { backgroundColor: `${colors.primary}10` }]}><Text style={{ color: colors.muted, fontSize: 13, fontWeight: "700" }}>Outstanding balance</Text><Text style={[styles.balance, { color: colors.text }]}>{formatKes(balance)}</Text><View style={styles.contactRow}><Pressable onPress={() => contact("tel")} accessibilityRole="button" style={({ pressed }) => [styles.contact, { backgroundColor: colors.surface, opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="call" size={18} color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Call</Text></Pressable><Pressable onPress={() => contact("sms")} accessibilityRole="button" style={({ pressed }) => [styles.contact, { backgroundColor: colors.surface, opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="message" size={18} color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Message</Text></Pressable></View></Card><Text style={[styles.section, { color: colors.text }]}>Record payment</Text><Field label="Amount received" value={amount} onChangeText={setAmount} placeholder="0" keyboardType="numeric" /><View style={styles.method}>{(["cash", "mpesa"] as const).map((item) => <Chip key={item} label={item === "mpesa" ? "M-Pesa" : "Cash"} selected={method === item} onPress={() => setMethod(item)} />)}</View><Field label="Note (optional)" value={paymentNote} onChangeText={setPaymentNote} placeholder="e.g. Paid via M-Pesa" /><PrimaryButton label="Save payment" icon="check-circle" onPress={record} disabled={balance <= 0} /><Text style={[styles.section, { color: colors.text }]}>History</Text>{[...sales.map((sale) => ({ id: sale.id, title: "Credit sale", detail: new Date(sale.saleDate).toLocaleDateString("en-KE"), amount: sale.totalAmount, positive: false })), ...payments.map((payment) => ({ id: payment.id, title: "Payment received", detail: new Date(payment.paymentDate).toLocaleDateString("en-KE"), amount: payment.amount, positive: true }))].sort((a, b) => b.id.localeCompare(a.id)).map((item) => <Card key={item.id} style={styles.history}><View><Text style={{ color: colors.text, fontWeight: "800" }}>{item.title}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>{item.detail}</Text></View><Text style={{ color: item.positive ? colors.success : colors.error, fontWeight: "800" }}>{item.positive ? "+" : "−"}{formatKes(item.amount)}</Text></Card>)}</Screen>;
}
const styles = StyleSheet.create({ balanceCard: { padding: 18 }, balance: { fontSize: 32, fontWeight: "800", marginTop: 5 }, contactRow: { flexDirection: "row", gap: 9, marginTop: 16 }, contact: { minHeight: 43, flex: 1, borderRadius: 13, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 7 }, section: { fontSize: 17, fontWeight: "800", marginTop: 21, marginBottom: 9 }, method: { flexDirection: "row", gap: 8, marginBottom: 14 }, history: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, marginBottom: 8 } });
