import { router, useLocalSearchParams } from "expo-router";
import { useState } from "react";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { Chip, Field, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { useColors } from "@/hooks/use-colors";
import { useStockbook } from "@/lib/stockbook/store";
import type { PaymentMethod } from "@/lib/stockbook/types";

const categories = ["Stock purchase", "Transport", "Rent", "Utilities", "Staff", "Other"];
export default function ExpenseFormScreen() {
  const { expenseId } = useLocalSearchParams<{ expenseId?: string }>();
  const { state, addExpense, updateExpense, deleteExpense } = useStockbook(); const colors = useColors(); const existing = state.expenses.find((expense) => expense.id === expenseId);
  const [title, setTitle] = useState(existing?.title ?? ""); const [amount, setAmount] = useState(existing ? String(existing.amount) : ""); const [category, setCategory] = useState(existing?.category ?? "Stock purchase"); const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>(existing?.paymentMethod ?? "cash"); const [date, setDate] = useState((existing?.expenseDate ?? new Date().toISOString()).slice(0, 10)); const [note, setNote] = useState(existing?.note ?? "");
  const save = () => { try { const input = { title, amount: Number(amount), category, paymentMethod, note: note.trim() || undefined, expenseDate: new Date(date).toISOString() }; if (existing) updateExpense(existing.id, input); else addExpense(input); router.back(); } catch (error) { Alert.alert("Could not save expense", error instanceof Error ? error.message : "Check the expense details."); } };
  const remove = () => { if (!existing) return; Alert.alert("Delete expense?", "This will remove the expense from your reports.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { deleteExpense(existing.id); router.back(); } }]); };
  return <Screen><TopBar title={existing ? "Edit expense" : "Add expense"} onBack={() => router.back()} /><Field label="Expense title" value={title} onChangeText={setTitle} placeholder="e.g. Delivery transport" /><Field label="Amount" value={amount} onChangeText={setAmount} placeholder="0" keyboardType="numeric" /><Text style={[styles.label, { color: colors.text }]}>Category</Text><View style={styles.wrap}>{categories.map((item) => <Chip key={item} label={item} selected={category === item} onPress={() => setCategory(item)} />)}</View><Text style={[styles.label, { color: colors.text }]}>Payment method</Text><View style={styles.wrap}>{(["cash", "mpesa", "bank", "other"] as const).map((item) => <Chip key={item} label={item === "mpesa" ? "M-Pesa" : item[0].toUpperCase() + item.slice(1)} selected={paymentMethod === item} onPress={() => setPaymentMethod(item)} />)}</View><Field label="Expense date" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" helper="Use the day the cost happened." /><Field label="Note (optional)" value={note} onChangeText={setNote} placeholder="Add a helpful note" multiline /><PrimaryButton label={existing ? "Save changes" : "Save expense"} icon="check-circle" onPress={save} />{existing ? <Pressable onPress={remove} accessibilityRole="button" style={styles.delete}><Text style={{ color: colors.error, fontWeight: "800" }}>Delete expense</Text></Pressable> : null}</Screen>;
}
const styles = StyleSheet.create({ label: { fontSize: 13, fontWeight: "700", marginBottom: 8 }, wrap: { flexDirection: "row", gap: 8, flexWrap: "wrap", marginBottom: 16 }, delete: { alignItems: "center", minHeight: 50, justifyContent: "center", marginTop: 13 } });
