import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Chip, EmptyState, LoadingScreen, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { expensesForPeriod, formatKes } from "@/lib/stockbook/calculations";
import { useStockbook } from "@/lib/stockbook/store";
import { useColors } from "@/hooks/use-colors";

type Period = "today" | "week" | "month";
export default function ExpensesScreen() {
  const { state, ready } = useStockbook(); const colors = useColors(); const [period, setPeriod] = useState<Period>("today");
  const expenses = expensesForPeriod(state, period); const total = expenses.reduce((sum, expense) => sum + expense.amount, 0);
  const grouped = useMemo(() => Array.from(new Set(expenses.map((expense) => expense.category))).map((category) => ({ category, items: expenses.filter((expense) => expense.category === category) })), [expenses]);
  if (!ready) return <LoadingScreen />;
  return <Screen><TopBar title="Expenses" onBack={() => router.back()} action={<Pressable accessibilityRole="button" accessibilityLabel="Add expense" onPress={() => router.push("/expense-form" as any)} style={({ pressed }) => [styles.add, { backgroundColor: colors.primary, opacity: pressed ? 0.7 : 1 }]}><MaterialIcons name="add" color="#FFFFFF" size={23} /></Pressable>} /><View style={styles.chips}>{(["today", "week", "month"] as const).map((item) => <Chip key={item} label={item[0].toUpperCase() + item.slice(1)} selected={period === item} onPress={() => setPeriod(item)} />)}</View><Card style={[styles.total, { backgroundColor: `${colors.error}10` }]}><Text style={{ color: colors.muted, fontWeight: "700", fontSize: 13 }}>{period === "today" ? "Today’s" : period === "week" ? "This week’s" : "This month’s"} expenses</Text><Text style={[styles.totalAmount, { color: colors.text }]}>{formatKes(total)}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{expenses.length} record{expenses.length === 1 ? "" : "s"}</Text></Card>{grouped.length ? grouped.map((group) => <View key={group.category} style={styles.group}><Text style={[styles.groupTitle, { color: colors.muted }]}>{group.category}</Text><Card style={styles.listCard}>{group.items.map((expense, index) => <Pressable key={expense.id} accessibilityRole="button" onPress={() => router.push({ pathname: "/expense-form" as any, params: { expenseId: expense.id } })} style={({ pressed }) => [styles.expenseRow, index !== group.items.length - 1 && { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }, { opacity: pressed ? 0.68 : 1 }]}><View style={[styles.expenseIcon, { backgroundColor: `${colors.error}14` }]}><MaterialIcons name="payments" size={18} color={colors.error} /></View><View style={{ flex: 1 }}><Text style={[styles.expenseTitle, { color: colors.text }]}>{expense.title}</Text><Text style={[styles.expenseMeta, { color: colors.muted }]}>{new Date(expense.expenseDate).toLocaleDateString("en-KE", { day: "numeric", month: "short" })} · {expense.paymentMethod === "mpesa" ? "M-Pesa" : expense.paymentMethod}</Text></View><Text style={{ color: colors.error, fontWeight: "800" }}>−{formatKes(expense.amount)}</Text></Pressable>)}</Card></View>) : <EmptyState icon="payments" title="No expenses yet" detail="Record transport, rent, restocking, or other business costs to see a clearer profit estimate." action={<PrimaryButton label="Add expense" icon="add" onPress={() => router.push("/expense-form" as any)} full={false} />} />}</Screen>;
}

const styles = StyleSheet.create({ add: { height: 44, width: 44, borderRadius: 14, alignItems: "center", justifyContent: "center" }, chips: { flexDirection: "row", gap: 8, marginBottom: 12 }, total: { padding: 18 }, totalAmount: { fontSize: 30, fontWeight: "800", marginTop: 5, marginBottom: 6, letterSpacing: -0.6 }, group: { marginTop: 21 }, groupTitle: { fontSize: 12, fontWeight: "800", textTransform: "uppercase", letterSpacing: 0.8, marginBottom: 8 }, listCard: { paddingVertical: 1 }, expenseRow: { flexDirection: "row", alignItems: "center", paddingVertical: 12, gap: 10 }, expenseIcon: { height: 38, width: 38, borderRadius: 12, alignItems: "center", justifyContent: "center" }, expenseTitle: { fontSize: 14, fontWeight: "800" }, expenseMeta: { fontSize: 12, marginTop: 3 } });
