import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Linking, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Screen, SectionTitle, TopBar } from "@/components/stockbook/ui";
import { useColors } from "@/hooks/use-colors";

const faqs = [
  ["Does the app work offline?", "Yes. M-Pesa StockBook stores your records locally on your device. Export a backup regularly if you want to keep a separate copy."],
  ["How is profit calculated?", "Estimated profit equals sale value less the recorded buying cost and business expenses. It depends on the prices you enter and is not formal accounting advice."],
  ["Can I import an M-Pesa statement?", "Yes. Use More → M-Pesa Import to select a CSV statement, check the column mapping, preview records, and import unique transaction codes."],
  ["Why is a product low in stock?", "A product is marked low when its quantity reaches the low-stock level you set in the product editor."],
];
export default function HelpScreen() { const colors = useColors(); return <Screen><TopBar title="Help & Support" onBack={() => router.back()} /><Card style={[styles.hero, { backgroundColor: `${colors.primary}10` }]}><View style={[styles.icon, { backgroundColor: `${colors.primary}18` }]}><MaterialIcons name="support-agent" color={colors.primary} size={27} /></View><Text style={[styles.heroTitle, { color: colors.text }]}>We’re here to help</Text><Text style={{ color: colors.muted, textAlign: "center", fontSize: 13, lineHeight: 19 }}>Start with these common questions, or contact your preferred support channel.</Text></Card><SectionTitle title="Common questions" />{faqs.map(([question, answer]) => <Card key={question} style={styles.faq}><Text style={{ color: colors.text, fontWeight: "800" }}>{question}</Text><Text style={{ color: colors.muted, fontSize: 13, lineHeight: 19, marginTop: 6 }}>{answer}</Text></Card>)}<SectionTitle title="Contact support" /><Card><Pressable accessibilityRole="button" onPress={() => void Linking.openURL("mailto:support@example.com?subject=M-Pesa%20StockBook%20help")} style={({ pressed }) => [styles.contact, { opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="email" color={colors.primary} size={20} /><Text style={{ color: colors.primary, fontWeight: "800", flex: 1 }}>Email support</Text><MaterialIcons name="chevron-right" color={colors.muted} size={21} /></Pressable></Card><Text style={[styles.note, { color: colors.muted }]}>M-Pesa StockBook is independent and not affiliated with Safaricom. Do not send your M-Pesa PIN or other sensitive details to support.</Text></Screen>; }
const styles = StyleSheet.create({ hero: { alignItems: "center", paddingVertical: 22 }, icon: { width: 55, height: 55, borderRadius: 17, alignItems: "center", justifyContent: "center", marginBottom: 12 }, heroTitle: { fontSize: 21, fontWeight: "800", marginBottom: 7 }, faq: { marginBottom: 9 }, contact: { minHeight: 50, flexDirection: "row", alignItems: "center", gap: 9 }, note: { textAlign: "center", fontSize: 11, lineHeight: 17, marginTop: 21, paddingHorizontal: 10 } });
