import * as DocumentPicker from "expo-document-picker";
import * as FileSystem from "expo-file-system/legacy";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Alert, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import { Card, Chip, KeyValue, LoadingScreen, PrimaryButton, Screen, SectionTitle, TopBar } from "@/components/stockbook/ui";
import { shareBackup } from "@/lib/stockbook/export";
import { useStockbook } from "@/lib/stockbook/store";
import type { StockbookState } from "@/lib/stockbook/types";
import { useColors } from "@/hooks/use-colors";

export default function SettingsScreen() {
  const { state, ready, updateSettings, replaceState, clearData } = useStockbook(); const colors = useColors();
  if (!ready) return <LoadingScreen />;
  const backup = async () => { try { await shareBackup(state); } catch (error) { Alert.alert("Could not export data", error instanceof Error ? error.message : "Try again on your device."); } };
  const restore = async () => { try { const result = await DocumentPicker.getDocumentAsync({ type: ["application/json", "text/json", "text/plain"], copyToCacheDirectory: true, multiple: false }); if (result.canceled) return; const content = await FileSystem.readAsStringAsync(result.assets[0].uri, { encoding: FileSystem.EncodingType.UTF8 }); const next = JSON.parse(content) as StockbookState; Alert.alert("Replace current data?", "Your current local data will be replaced by this backup. This cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Replace data", style: "destructive", onPress: () => { try { replaceState(next); Alert.alert("Data restored", "Your local backup has been restored."); } catch (error) { Alert.alert("Backup not accepted", error instanceof Error ? error.message : "Please choose a valid M-Pesa StockBook backup."); } } }]); } catch (error) { Alert.alert("Could not read backup", error instanceof Error ? error.message : "Choose a valid JSON backup file."); } };
  const erase = () => Alert.alert("Clear all local data?", "This permanently removes your business profile, products, sales, expenses, customers, imported M-Pesa transactions, and settings from this device.", [{ text: "Cancel", style: "cancel" }, { text: "Clear all data", style: "destructive", onPress: () => { clearData(); router.replace("/onboarding"); } }]);
  return <Screen><TopBar title="Settings" onBack={() => router.back()} /><SectionTitle title="Business profile" /><Card><KeyValue label="Business" value={state.profile?.businessName || "Not set"} /><KeyValue label="Type" value={state.profile?.businessType || "Not set"} /><KeyValue label="Opening cash" value={`KSh ${state.profile?.defaultOpeningBalance ?? 0}`} /><Pressable accessibilityRole="button" onPress={() => router.push({ pathname: "/onboarding", params: { mode: "edit" } } as any)} style={({ pressed }) => [styles.edit, { opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="edit" size={17} color={colors.primary} /><Text style={{ color: colors.primary, fontWeight: "800" }}>Edit business details</Text></Pressable></Card><SectionTitle title="Appearance" /><Card><Text style={{ color: colors.text, fontWeight: "800", marginBottom: 10 }}>Theme</Text><View style={styles.themeRow}>{(["light", "dark"] as const).map((item) => <Chip key={item} label={item[0].toUpperCase() + item.slice(1)} selected={state.settings.colorScheme === item} onPress={() => updateSettings({ colorScheme: item })} />)}</View></Card><SectionTitle title="Stock handling" /><Card><View style={styles.switchRow}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "800" }}>Allow negative stock</Text><Text style={{ color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }}>Only enable this if you sell items before recording their stock.</Text></View><Switch value={state.settings.allowNegativeStock} onValueChange={(value) => updateSettings({ allowNegativeStock: value })} trackColor={{ false: colors.border, true: `${colors.primary}88` }} thumbColor={state.settings.allowNegativeStock ? colors.primary : colors.surface} /></View></Card><SectionTitle title="Your data" /><Card style={styles.dataCard}><PrimaryButton label="Export backup" icon="ios-share" tone="quiet" onPress={() => void backup()} /><PrimaryButton label="Restore from backup" icon="file-upload" tone="quiet" onPress={() => void restore()} /><Text style={{ color: colors.muted, fontSize: 12, lineHeight: 17, textAlign: "center", marginTop: 13 }}>A backup is a JSON file containing your local app data. Keep it somewhere private.</Text></Card><SectionTitle title="Support" /><Card style={styles.dataCard}><PrimaryButton label="Open Help & Support" icon="help-outline" tone="quiet" onPress={() => router.push("/help" as any)} /><PrimaryButton label="Upgrade options" icon="workspace-premium" tone="quiet" onPress={() => router.push("/upgrade" as any)} /></Card><Pressable accessibilityRole="button" onPress={erase} style={styles.erase}><Text style={{ color: colors.error, fontWeight: "800" }}>Clear all local data</Text></Pressable></Screen>;
}
const styles = StyleSheet.create({ edit: { flexDirection: "row", gap: 6, alignItems: "center", marginTop: 9, minHeight: 36 }, themeRow: { flexDirection: "row", gap: 8 }, switchRow: { flexDirection: "row", alignItems: "center", gap: 12 }, dataCard: { paddingBottom: 5 }, erase: { minHeight: 55, alignItems: "center", justifyContent: "center", marginTop: 18 } });
