import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Pressable, StyleSheet, Text, View } from "react-native";
import { Card, KeyValue, LoadingScreen, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { formatKes } from "@/lib/stockbook/calculations";
import { receiptText, shareText } from "@/lib/stockbook/export";
import { useStockbook } from "@/lib/stockbook/store";
import { useColors } from "@/hooks/use-colors";

export default function TransactionDetailsScreen() {
  const { id, type } = useLocalSearchParams<{ id: string; type: string }>(); const { state, ready, deleteSale, deleteExpense, deleteCreditPayment } = useStockbook(); const colors = useColors();
  if (!ready) return <LoadingScreen />;
  const remove = (title: string, action: () => void) => Alert.alert(`Delete ${title}?`, "This action cannot be undone. The related totals will update immediately.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => { action(); router.back(); } }]);
  if (type === "sale") { const sale = state.sales.find((entry) => entry.id === id); if (!sale) return <Missing />; return <Screen><TopBar title="Sale details" onBack={() => router.back()} /><Card style={styles.total}><Text style={{ color: colors.muted, fontSize: 13 }}>Total received</Text><Text style={[styles.amount, { color: colors.success }]}>{formatKes(sale.totalAmount)}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{new Date(sale.saleDate).toLocaleString("en-KE")}</Text></Card><Card><KeyValue label="Payment" value={sale.paymentMethod === "mpesa" ? "M-Pesa" : sale.paymentMethod} /><KeyValue label="Estimated profit" value={formatKes(sale.estimatedProfit)} positive /><KeyValue label="Discount" value={formatKes(sale.discount)} />{sale.mpesaCode ? <KeyValue label="M-Pesa code" value={sale.mpesaCode} /> : null}{sale.notes ? <KeyValue label="Note" value={sale.notes} /> : null}</Card><Text style={[styles.section, { color: colors.text }]}>Items sold</Text><Card>{sale.items.map((item) => <View key={item.id} style={styles.item}><View style={{ flex: 1 }}><Text style={{ color: colors.text, fontWeight: "800" }}>{item.productNameSnapshot}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>{item.quantity} × {formatKes(item.sellingPriceSnapshot)}</Text></View><Text style={{ color: colors.text, fontWeight: "800" }}>{formatKes(item.subtotal)}</Text></View>)}</Card><PrimaryButton label="Share receipt" icon="share" onPress={() => void shareText("Sale receipt", receiptText(state, sale.id))} /><Pressable accessibilityRole="button" onPress={() => remove("sale", () => deleteSale(sale.id))} style={styles.delete}><Text style={{ color: colors.error, fontWeight: "800" }}>Delete sale and restore stock</Text></Pressable></Screen>; }
  if (type === "expense") { const expense = state.expenses.find((entry) => entry.id === id); if (!expense) return <Missing />; return <Screen><TopBar title="Expense details" onBack={() => router.back()} /><Card style={styles.total}><Text style={{ color: colors.muted, fontSize: 13 }}>{expense.category}</Text><Text style={[styles.amount, { color: colors.error }]}>−{formatKes(expense.amount)}</Text><Text style={{ color: colors.muted, fontSize: 12 }}>{new Date(expense.expenseDate).toLocaleDateString("en-KE")}</Text></Card><Card><KeyValue label="Title" value={expense.title} /><KeyValue label="Payment" value={expense.paymentMethod === "mpesa" ? "M-Pesa" : expense.paymentMethod} />{expense.note ? <KeyValue label="Note" value={expense.note} /> : null}</Card><PrimaryButton label="Edit expense" icon="edit" onPress={() => router.push({ pathname: "/expense-form" as any, params: { expenseId: expense.id } })} /><Pressable accessibilityRole="button" onPress={() => remove("expense", () => deleteExpense(expense.id))} style={styles.delete}><Text style={{ color: colors.error, fontWeight: "800" }}>Delete expense</Text></Pressable></Screen>; }
  if (type === "credit-payment") { const payment = state.creditPayments.find((entry) => entry.id === id); if (!payment) return <Missing />; const customer = state.customers.find((entry) => entry.id === payment.customerId); return <Screen><TopBar title="Credit payment" onBack={() => router.back()} /><Card style={styles.total}><Text style={{ color: colors.muted, fontSize: 13 }}>Payment received</Text><Text style={[styles.amount, { color: colors.success }]}>{formatKes(payment.amount)}</Text></Card><Card><KeyValue label="Customer" value={customer?.name || "Unknown customer"} /><KeyValue label="Method" value={payment.paymentMethod === "mpesa" ? "M-Pesa" : payment.paymentMethod} /><KeyValue label="Date" value={new Date(payment.paymentDate).toLocaleDateString("en-KE")} />{payment.note ? <KeyValue label="Note" value={payment.note} /> : null}</Card><Pressable accessibilityRole="button" onPress={() => remove("credit payment", () => deleteCreditPayment(payment.id))} style={styles.delete}><Text style={{ color: colors.error, fontWeight: "800" }}>Delete payment</Text></Pressable></Screen>; }
  const adjustment = state.stockAdjustments.find((entry) => entry.id === id); if (!adjustment) return <Missing />; const product = state.products.find((entry) => entry.id === adjustment.productId); return <Screen><TopBar title="Stock adjustment" onBack={() => router.back()} /><Card><KeyValue label="Product" value={product?.name || "Archived product"} /><KeyValue label="Change" value={`${adjustment.quantityChange > 0 ? "+" : ""}${adjustment.quantityChange}`} positive={adjustment.quantityChange > 0} /><KeyValue label="Stock before" value={String(adjustment.quantityBefore)} /><KeyValue label="Stock after" value={String(adjustment.quantityAfter)} /><KeyValue label="Reason" value={adjustment.reason} /></Card></Screen>;
}
function Missing() { const colors = useColors(); return <Screen><TopBar title="Transaction" onBack={() => router.back()} /><View style={styles.missing}><MaterialIcons name="error-outline" size={30} color={colors.muted} /><Text style={{ color: colors.muted }}>This transaction is no longer available.</Text></View></Screen>; }
const styles = StyleSheet.create({ total: { alignItems: "center", paddingVertical: 22 }, amount: { fontSize: 31, fontWeight: "800", marginTop: 5, marginBottom: 5 }, section: { fontSize: 17, fontWeight: "800", marginTop: 20, marginBottom: 9 }, item: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 9 }, delete: { minHeight: 52, justifyContent: "center", alignItems: "center", marginTop: 12 }, missing: { alignItems: "center", paddingVertical: 50, gap: 11 } });
