import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, Chip, EmptyState, LoadingScreen, Screen, TopBar } from "@/components/stockbook/ui";
import { buildTimeline, formatKes } from "@/lib/stockbook/calculations";
import { useStockbook } from "@/lib/stockbook/store";
import { useColors } from "@/hooks/use-colors";
import type { TimelineItem } from "@/lib/stockbook/types";

type Filter = "all" | TimelineItem["type"];
export default function TransactionsScreen() {
  const { state, ready } = useStockbook(); const colors = useColors(); const [filter, setFilter] = useState<Filter>("all"); const [payment, setPayment] = useState("all");
  const timeline = useMemo(() => buildTimeline(state).filter((item) => (filter === "all" || item.type === filter) && (payment === "all" || item.paymentMethod === payment)), [state, filter, payment]);
  if (!ready) return <LoadingScreen />;
  return <Screen><TopBar title="Transactions" subtitle="Sales, expenses and stock changes" onBack={() => router.back()} /><Text style={[styles.label, { color: colors.muted }]}>TYPE</Text><View style={styles.wrap}>{(["all", "sale", "expense", "stock", "credit-payment"] as const).map((item) => <Chip key={item} label={item === "all" ? "All" : item === "credit-payment" ? "Credit paid" : item[0].toUpperCase() + item.slice(1)} selected={filter === item} onPress={() => setFilter(item)} />)}</View><Text style={[styles.label, { color: colors.muted }]}>PAYMENT</Text><View style={styles.wrap}>{(["all", "cash", "mpesa", "credit"] as const).map((item) => <Chip key={item} label={item === "all" ? "All methods" : item === "mpesa" ? "M-Pesa" : item[0].toUpperCase() + item.slice(1)} selected={payment === item} onPress={() => setPayment(item)} />)}</View>{timeline.length ? <Card style={styles.list}>{timeline.map((item, index) => <Pressable key={`${item.type}-${item.id}`} accessibilityRole="button" onPress={() => router.push({ pathname: "/transaction-details" as any, params: { id: item.id, type: item.type } })} style={({ pressed }) => [styles.row, index !== timeline.length - 1 && { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, { opacity: pressed ? 0.68 : 1 }]}><View style={[styles.icon, { backgroundColor: item.positive ? `${colors.success}18` : `${colors.error}14` }]}><MaterialIcons name={item.type === "sale" ? "receipt-long" : item.type === "expense" ? "payments" : item.type === "stock" ? "inventory" : "person"} size={19} color={item.positive ? colors.success : colors.error} /></View><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.rowMeta, { color: colors.muted }]}>{item.subtitle} · {new Date(item.date).toLocaleDateString("en-KE", { day: "numeric", month: "short" })}</Text></View><View style={styles.right}>{item.amount !== undefined ? <Text style={{ color: item.positive ? colors.success : colors.error, fontWeight: "800" }}>{item.positive ? "+" : "−"}{formatKes(item.amount)}</Text> : null}<MaterialIcons name="chevron-right" size={20} color={colors.muted} /></View></Pressable>)}</Card> : <EmptyState icon="receipt-long" title="No matching transactions" detail="Try another filter or add a sale, expense, or stock adjustment." />}</Screen>;
}
const styles = StyleSheet.create({ label: { fontSize: 11, letterSpacing: 0.9, fontWeight: "800", marginBottom: 7 }, wrap: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 15 }, list: { paddingVertical: 2 }, row: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10 }, icon: { height: 39, width: 39, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowTitle: { fontWeight: "800", fontSize: 14 }, rowMeta: { fontSize: 11, marginTop: 3 }, right: { alignItems: "flex-end", gap: 3 } });
