import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { StyleSheet, Text, View } from "react-native";
import { Card, PrimaryButton, Screen, TopBar } from "@/components/stockbook/ui";
import { useColors } from "@/hooks/use-colors";

export default function UpgradeScreen() { const colors = useColors(); return <Screen><TopBar title="Upgrade" onBack={() => router.back()} /><View style={styles.hero}><View style={[styles.icon, { backgroundColor: `${colors.warning}18` }]}><MaterialIcons name="workspace-premium" color={colors.warning} size={39} /></View><Text style={[styles.title, { color: colors.text }]}>More room to grow</Text><Text style={[styles.detail, { color: colors.muted }]}>You are using the free starter plan, which supports up to 30 products and 50 recorded sales per calendar month.</Text></View><Card><Feature text="Unlimited products and sales" /><Feature text="Advanced reports and exports" /><Feature text="Additional business tools when available" /></Card><Text style={[styles.note, { color: colors.muted }]}>Purchasing is not available in this version. When upgrades are enabled, this page will show clear pricing and a secure payment flow before any charge is made.</Text><PrimaryButton label="Back to StockBook" icon="arrow-back" tone="quiet" onPress={() => router.back()} /></Screen>; }
function Feature({ text }: { text: string }) { const colors = useColors(); return <View style={styles.feature}><MaterialIcons name="check-circle" color={colors.success} size={18} /><Text style={{ color: colors.text, fontWeight: "700", flex: 1 }}>{text}</Text></View>; }
const styles = StyleSheet.create({ hero: { alignItems: "center", paddingVertical: 29 }, icon: { width: 82, height: 82, borderRadius: 27, alignItems: "center", justifyContent: "center", marginBottom: 14 }, title: { fontSize: 25, fontWeight: "800" }, detail: { fontSize: 14, textAlign: "center", lineHeight: 21, maxWidth: 320, marginTop: 8 }, feature: { flexDirection: "row", gap: 9, alignItems: "center", paddingVertical: 10 }, note: { textAlign: "center", fontSize: 12, lineHeight: 18, marginTop: 17 } });
