import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { router } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { Card, LoadingScreen, Screen, SectionTitle } from "@/components/stockbook/ui";
import { useColors } from "@/hooks/use-colors";
import { useStockbook } from "@/lib/stockbook/store";

const items = [
  { icon: "group" as const, title: "Credit Book", detail: "Customers and repayments", route: "/credit" },
  { icon: "payments" as const, title: "Expenses", detail: "Business costs and categories", route: "/expenses" },
  { icon: "receipt-long" as const, title: "Transactions", detail: "Sales, expenses and stock", route: "/transactions" },
  { icon: "file-upload" as const, title: "M-Pesa Import", detail: "Import a statement CSV", route: "/mpesa-import" },
];
export default function MoreScreen() {
  const { state, ready } = useStockbook(); const colors = useColors(); if (!ready) return <LoadingScreen />;
  return <Screen><View style={styles.header}><View><Text style={[styles.title, { color: colors.text }]}>More</Text><Text style={{ color: colors.muted, marginTop: 3 }}>{state.profile?.businessName || "M-Pesa StockBook"}</Text></View><Pressable accessibilityRole="button" onPress={() => router.push("/settings" as any)} style={({ pressed }) => [styles.settings, { backgroundColor: `${colors.primary}16`, opacity: pressed ? 0.68 : 1 }]}><MaterialIcons name="settings" size={21} color={colors.primary} /></Pressable></View><Card style={styles.list}>{items.map((item, index) => <Pressable key={item.title} accessibilityRole="button" onPress={() => router.push(item.route as any)} style={({ pressed }) => [styles.row, index !== items.length - 1 && { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, { opacity: pressed ? 0.67 : 1 }]}><View style={[styles.icon, { backgroundColor: `${colors.primary}16` }]}><MaterialIcons name={item.icon} size={20} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={[styles.rowTitle, { color: colors.text }]}>{item.title}</Text><Text style={{ color: colors.muted, fontSize: 12, marginTop: 3 }}>{item.detail}</Text></View><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></Pressable>)}</Card><SectionTitle title="App" /><Card style={styles.list}><Menu title="Settings" icon="tune" route="/settings" /><Menu title="Help & support" icon="help-outline" route="/help" last /><Menu title="Upgrade" icon="workspace-premium" route="/upgrade" last /></Card><View style={styles.disclaimer}><Text style={{ color: colors.muted, fontSize: 11, textAlign: "center", lineHeight: 17 }}>M-Pesa StockBook is an independent tool and is not affiliated with Safaricom. Your business data is stored locally on this device.</Text></View></Screen>;
}
function Menu({ title, icon, route, last }: { title: string; icon: React.ComponentProps<typeof MaterialIcons>["name"]; route: string; last?: boolean }) { const colors = useColors(); return <Pressable accessibilityRole="button" onPress={() => router.push(route as any)} style={({ pressed }) => [styles.row, !last && { borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, { opacity: pressed ? 0.67 : 1 }]}><View style={[styles.icon, { backgroundColor: colors.background }]}><MaterialIcons name={icon} size={20} color={colors.primary} /></View><Text style={[styles.rowTitle, { color: colors.text, flex: 1 }]}>{title}</Text><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></Pressable>; }
const styles = StyleSheet.create({ header: { paddingTop: 10, flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 15 }, title: { fontSize: 25, fontWeight: "800", letterSpacing: -0.5 }, settings: { height: 43, width: 43, borderRadius: 14, alignItems: "center", justifyContent: "center" }, list: { paddingVertical: 1 }, row: { minHeight: 67, flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10 }, icon: { height: 39, width: 39, borderRadius: 12, alignItems: "center", justifyContent: "center" }, rowTitle: { fontWeight: "800", fontSize: 14 }, disclaimer: { paddingHorizontal: 18, paddingVertical: 24 } });
